research_task:
  description: >
    Conduct a thorough research of {company_name} and prepare a brief that will be used by an Account Executive to present to a potential client.
    Make sure to only utilize information that is relevant within the current year 2025.
    Focus on information such as:
    - Company description
    - Company goals
    - Company performance
    - Company competitors
    - Company market position
    - Company financials
    - Company news
  expected_output: >
    A list of 10 bullet points of the most relevant information about {company_name}.
  agent: analyst

reporting_task:
  description: >
    Review the content you received and expand on it to create a detailed report that will be used by an Account Executive to present to a potential client.
    Make sure the report is detailed and contains all the relevant information about {company_name}.
  expected_output: >
    A detailed report of the most relevant information about {company_name}, formatted in Markdown.
  agent: analyst
  output_file: report.md